import { Product, Category, RecipeBundle } from '../types';

export const CATEGORIES: Category[] = [
  { id: 'cat1', name: 'Мах, махан бүтээгдэхүүн', slug: 'meat', icon: '🥩', itemCount: 42 },
  { id: 'cat2', name: 'Хүнсний ногоо', slug: 'vegetables', icon: '🥦', itemCount: 38 },
  { id: 'cat3', name: 'Сүүн бүтээгдэхүүн', slug: 'dairy', icon: '🥛', itemCount: 29 },
  { id: 'cat4', name: 'Гурилан бүтээгдэхүүн', slug: 'bakery', icon: '🍞', itemCount: 24 },
  { id: 'cat5', name: 'Жимс, жимсгэнэ', slug: 'fruits', icon: '🍎', itemCount: 31 },
  { id: 'cat6', name: 'Ундаа, ус', slug: 'drinks', icon: '🥤', itemCount: 45 },
  { id: 'cat7', name: 'Амттан, чипс', slug: 'snacks', icon: '🍫', itemCount: 50 },
  { id: 'cat8', name: 'Соус, амтлагч', slug: 'spices', icon: '🧂', itemCount: 26 },
  { id: 'cat9', name: 'Ахуйн бараа', slug: 'household', icon: '🧻', itemCount: 60 },
  { id: 'cat10', name: 'Согтууруулах ундаа', slug: 'alcohol', icon: '🍷', itemCount: 18 },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    odooId: 101,
    sku: "ODOO-MEAT-001",
    name: "Үхрийн цул мах (1кг)",
    price: 17500,
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600&q=80",
    category: "Мах, махан бүтээгдэхүүн",
    categorySlug: "meat",
    description: "Шинэхэн монгол үхрийн цул мах. Гурилтай шөл, цуйван болон хуурганд маш тохиромжтой.",
    expiration: "Хадгалах хугацаа: 3 хоног (хөргөгчинд +2°C..+4°C)",
    stock: 45,
    unit: "кг",
    brand: "Мах Импэкс",
    isMongolian: true,
    tags: ["Шинэхэн", "Монгол мах", "Уураг өндөр"]
  },
  {
    id: "p2",
    odooId: 102,
    sku: "ODOO-MEAT-002",
    name: "Хонины ястай мах (1кг)",
    price: 13500,
    discountPrice: 12200,
    image: "https://images.unsplash.com/photo-1603048297172-c92544798d5e?w=600&q=80",
    category: "Мах, махан бүтээгдэхүүн",
    categorySlug: "meat",
    description: "Шөлний зориулалттай шинэхэн хонины ястай мах. Амтлаг, шим тэжээлтэй.",
    expiration: "Хадгалах хугацаа: 3 хоног",
    stock: 30,
    unit: "кг",
    brand: "Орон нутгийн ферм",
    isMongolian: true,
    tags: ["Шөлний мах", "Хямдралтай"]
  },
  {
    id: "p3",
    odooId: 103,
    sku: "ODOO-MEAT-003",
    name: "Тахианы цээж мах (1кг)",
    price: 12000,
    discountPrice: 10500,
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&q=80",
    category: "Мах, махан бүтээгдэхүүн",
    categorySlug: "meat",
    description: "Өөх тос багатай, цэвэр уургаар баялаг эрүүл мэндэд тустай тахианы цээж мах.",
    calories: "165 kcal / 100g",
    expiration: "Хадгалах хугацаа: 5 хоног",
    stock: 55,
    unit: "кг",
    brand: "NVC",
    isOrganic: true,
    tags: ["Эрүүл хоол", "Уураглаг", "Хямдралтай"]
  },
  {
    id: "p4",
    odooId: 104,
    sku: "ODOO-VEG-001",
    name: "Монгол төмс (1кг)",
    price: 1500,
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&q=80",
    category: "Хүнсний ногоо",
    categorySlug: "vegetables",
    description: "Шинэ ургацын Монгол хөрсний төмс. Хоолны бүх төрлийн хэрэглээнд тохиромжтой.",
    calories: "77 kcal / 100g",
    expiration: "Хадгалах хугацаа: 30 хоног",
    stock: 200,
    unit: "кг",
    brand: "Сэлэнгэ ургац",
    isMongolian: true,
    isOrganic: true,
    tags: ["Органик", "Монгол ургац"]
  },
  {
    id: "p5",
    odooId: 105,
    sku: "ODOO-VEG-002",
    name: "Сонгино шар (1кг)",
    price: 3500,
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&q=80",
    category: "Хүнсний ногоо",
    categorySlug: "vegetables",
    description: "Хоолны амт оруулагч шар сонгино.",
    expiration: "Хадгалах хугацаа: 60 хоног",
    stock: 180,
    unit: "кг",
    brand: "Сэлэнгэ ургац",
    isMongolian: true,
    tags: ["Монгол ургац"]
  },
  {
    id: "p6",
    odooId: 106,
    sku: "ODOO-VEG-003",
    name: "Шинэхэн Лууван (1кг)",
    price: 2000,
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=600&q=80",
    category: "Хүнсний ногоо",
    categorySlug: "vegetables",
    description: "Амин дэм А, бета-каротитоор баялаг амтлаг шинэхэн лууван.",
    calories: "41 kcal / 100g",
    expiration: "Хадгалах хугацаа: 30 хоног",
    stock: 140,
    unit: "кг",
    brand: "Борнуур",
    isMongolian: true,
    isOrganic: true,
    tags: ["Витамин C", "Монгол ургац"]
  },
  {
    id: "p7",
    odooId: 107,
    sku: "ODOO-DAIRY-001",
    name: "Сүү 3.2% (1л) - АПУ Дээж",
    price: 3800,
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&q=80",
    category: "Сүүн бүтээгдэхүүн",
    categorySlug: "dairy",
    description: "Пастеризуулсан үнээний цэвэр сүү. Өглөөний цай болон хоолонд ашиглахад нэн тохиромжтой.",
    ingredients: "Үнээний цэвэр сүү 100%",
    calories: "60 kcal / 100ml",
    expiration: "Хадгалах хугацаа: 14 хоног",
    stock: 90,
    unit: "л",
    brand: "АПУ Дээж",
    isMongolian: true,
    tags: ["Монгол үйлдвэр", "Пастеризуулсан"]
  },
  {
    id: "p8",
    odooId: 108,
    sku: "ODOO-DAIRY-002",
    name: "Өндөг (10 ширхэг)",
    price: 5500,
    image: "https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=600&q=80",
    category: "Сүүн бүтээгдэхүүн",
    categorySlug: "dairy",
    description: "Төгс чанарын фермийн шинэхэн өндөг.",
    calories: "155 kcal / 100g",
    expiration: "Хадгалах хугацаа: 21 хоног",
    stock: 120,
    unit: "хайрцаг",
    brand: "Баян өндөг",
    isMongolian: true,
    tags: ["Фермийн шинэ"]
  },
  {
    id: "p9",
    odooId: 109,
    sku: "ODOO-BAKERY-001",
    name: "Атар талх (Зүссэн)",
    price: 2400,
    image: "https://images.unsplash.com/photo-1598373182133-52452f7691ef?w=600&q=80",
    category: "Гурилан бүтээгдэхүүн",
    categorySlug: "bakery",
    description: "Өдөр бүр шинээр барьсан Монголын уламжлалт зүсмэл Атар талх.",
    calories: "265 kcal / 100g",
    expiration: "Хадгалах хугацаа: 3 хоног",
    stock: 80,
    unit: "ш",
    brand: "Талх Чихэр",
    isMongolian: true,
    tags: ["Шинэ талх"]
  },
  {
    id: "p10",
    odooId: 110,
    sku: "ODOO-SPICE-001",
    name: "Гурилын дээд зэрэг (2кг) - Алтан Тариа",
    price: 5000,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80",
    category: "Гурилан бүтээгдэхүүн",
    categorySlug: "bakery",
    description: "Бууз, банш, цуйван, талх нарийн бовч хийхэд тохиромжтой дээд зэргийн улаан буудайн гурил.",
    expiration: "Хадгалах хугацаа: 1 жил",
    stock: 150,
    unit: "уут",
    brand: "Алтан Тариа",
    isMongolian: true,
    tags: ["Дээд зэрэг", "Zity Chef Тохиромжтой"]
  },
  {
    id: "p11",
    odooId: 111,
    sku: "ODOO-VEG-004",
    name: "Улаан лооль (1кг)",
    price: 8500,
    discountPrice: 7200,
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&q=80",
    category: "Хүнсний ногоо",
    categorySlug: "vegetables",
    description: "Шүүслэг, амтлаг органик улаан лооль. Салад болон соусанд тохиромжтой.",
    calories: "18 kcal / 100g",
    expiration: "Хадгалах хугацаа: 7 хоног",
    stock: 65,
    unit: "кг",
    brand: "Номин Органик",
    isOrganic: true,
    tags: ["Органик", "Хямдралтай"]
  },
  {
    id: "p12",
    odooId: 112,
    sku: "ODOO-FRUIT-001",
    name: "Гадил жимс (1кг)",
    price: 8500,
    image: "https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=600&q=80",
    category: "Жимс, жимсгэнэ",
    categorySlug: "fruits",
    description: "Калиар баялаг, энергийн эх үүсвэр шинэхэн гадил жимс.",
    calories: "89 kcal / 100g",
    expiration: "Хадгалах хугацаа: 5 хоног",
    stock: 95,
    unit: "кг",
    brand: "Импорт",
    tags: ["Витамин", "Амттан"]
  },
  {
    id: "p13",
    odooId: 113,
    sku: "ODOO-DAIRY-003",
    name: "Цөцгийн тос 82.5% (200г)",
    price: 6500,
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&q=80",
    category: "Сүүн бүтээгдэхүүн",
    categorySlug: "dairy",
    description: "Уламжлалт аргаар бэлтгэсэн цэвэр цөцгийн тос.",
    expiration: "Хадгалах хугацаа: 3 сар",
    stock: 40,
    unit: "ш",
    brand: "Цэвэр Сүү",
    isMongolian: true,
    tags: ["Цэвэр тос"]
  },
  {
    id: "p14",
    odooId: 114,
    sku: "ODOO-DRINK-001",
    name: "Жүржийн цэвэр шүүс (1л) - Cappy",
    price: 5500,
    discountPrice: 4800,
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600&q=80",
    category: "Ундаа, ус",
    categorySlug: "drinks",
    description: "Витамин С-ээр баялаг 100% жүржийн шүүс.",
    calories: "45 kcal / 100ml",
    expiration: "Хадгалах хугацаа: 1 жил",
    stock: 75,
    unit: "ш",
    brand: "Cappy",
    tags: ["Витамин С", "100% Шүүс"]
  },
  {
    id: "p15",
    odooId: 115,
    sku: "ODOO-DRINK-002",
    name: "Цэвэр ус Bonaqua (1.5л)",
    price: 1500,
    image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=600&q=80",
    category: "Ундаа, ус",
    categorySlug: "drinks",
    description: "Эрдэст цэвэр байгалийн ус.",
    stock: 300,
    unit: "ш",
    brand: "Coca-Cola Bottlers",
    tags: ["Цэвэр ус"]
  }
];

export const RECIPE_BUNDLES: RecipeBundle[] = [
  {
    id: "b1",
    recipeId: "rec-tsuivan",
    name: "Монгол уламжлалт Цуйван багц",
    chefName: "Chef Zity",
    description: "4 хүний порцтой шинэ үхрийн мах, лууван, сонгино, гурилын иж бүрдэл",
    prepTime: "35 мин",
    servings: 4,
    price: 27900,
    discountPrice: 24900,
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80",
    productItems: [
      { productId: "p1", productName: "Үхрийн цул мах (1кг)", requiredQty: 1, unit: "кг", pricePerUnit: 17500 },
      { productId: "p5", productName: "Сонгино шар (1кг)", requiredQty: 1, unit: "кг", pricePerUnit: 3500 },
      { productId: "p6", productName: "Шинэхэн Лууван (1кг)", requiredQty: 1, unit: "кг", pricePerUnit: 2000 },
      { productId: "p10", productName: "Гурилын дээд зэрэг (2кг)", requiredQty: 1, unit: "уут", pricePerUnit: 5000 }
    ],
    instructions: [
      "1. Гурилаа бүлээн усаар зуурч 15 мин амраана.",
      "2. Үхрийн махаа нарийн хэрчиж сонгинотой хамт хуурна.",
      "3. Гурилаа нимгэн элдэн жигнэж, зүсэж ногоо махтайгаа холино."
    ]
  },
  {
    id: "b2",
    recipeId: "rec-breakfast",
    name: "Zity Өглөөний цайны тансаг багц",
    chefName: "Chef Zity",
    description: "Шинэ өндөг, сүү, атар талх, цөцгийн тостой 4 хүний өглөөний цай",
    prepTime: "15 мин",
    servings: 4,
    price: 18100,
    discountPrice: 15900,
    image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=600&q=80",
    productItems: [
      { productId: "p8", productName: "Өндөг (10 ширхэг)", requiredQty: 1, unit: "хайрцаг", pricePerUnit: 5500 },
      { productId: "p7", productName: "Сүү 3.2% (1л)", requiredQty: 1, unit: "л", pricePerUnit: 3800 },
      { productId: "p9", productName: "Атар талх (Зүссэн)", requiredQty: 1, unit: "ш", pricePerUnit: 2400 },
      { productId: "p13", productName: "Цөцгийн тос 82.5% (200г)", requiredQty: 1, unit: "ш", pricePerUnit: 6500 }
    ],
    instructions: [
      "1. Өндгөө цөцгийн тосонд зөөлөн шарж бэлтгэнэ.",
      "2. Талхаа цөцгийн тосоор түрхэж халаана.",
      "3. Халуун сүү эсвэл кофетой хамт таваглана."
    ]
  },
  {
    id: "b3",
    recipeId: "rec-healthy-salad",
    name: "Органик Шинэ Ногооны Салад багц",
    chefName: "Chef Zity",
    description: "Улаан лооль, лууван, гадил жимс, цэвэр шүүстэй эрүүл хооллолтын багц",
    prepTime: "10 мин",
    servings: 2,
    price: 24500,
    discountPrice: 21500,
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&q=80",
    productItems: [
      { productId: "p11", productName: "Улаан лооль (1кг)", requiredQty: 1, unit: "кг", pricePerUnit: 7200 },
      { productId: "p6", productName: "Шинэхэн Лууван (1кг)", requiredQty: 1, unit: "кг", pricePerUnit: 2000 },
      { productId: "p12", productName: "Гадил жимс (1кг)", requiredQty: 1, unit: "кг", pricePerUnit: 8500 },
      { productId: "p14", productName: "Жүржийн цэвэр шүүс (1л)", requiredQty: 1, unit: "ш", pricePerUnit: 4800 }
    ],
    instructions: [
      "1. Ногоогоо угааж шоо дөрвөлжин хэрчинэ.",
      "2. Жимс болон шүүстэй хамт өглөөний эсвэл өдрийн хоолонд хэрэглэнэ."
    ]
  }
];
